backend:
  name: github
  repo: dcorn068/hyeranart

# https://www.netlifycms.org/docs/configuration-options/#media-library
media_folder: static/images/uploads
public_folder: images/uploads
media_library:
  name: cloudinary
  config:
    cloud_name: dypooxy9q
    api_key: 857318985278727
    multiple: true
site_url: https://hyeranart.netlify.com

collections:
  - name: pages
    label: Pages
    files:
      - file: "src/pages/landing/index.md"
        name: landingPage
        label: Landing Page (Open Page)
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "landing-page",
            }
          - { name: title, label: Title, widget: string }
          - { name: Image, label: Cover Image, widget: image }
      - file: "src/pages/second/index.md"
        name: secondPage
        label: Second Page (after Landing Page)
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "second-page",
            }
          - { name: title, label: Title, widget: string }
          - { name: Image, label: Top Image, widget: image }
          - { label: Body, name: body, widget: markdown }
          - label: Contact Links
            name: contactLinks
            widget: list
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Web Address (Link), name: link, widget: string }
      - file: "src/pages/about/index.md"
        name: aboutPage
        label: About Page
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "about-page",
            }
          - { label: Title, name: title, widget: string }
          - { label: Body, name: body, widget: markdown }
  - name: painting
    label: Single Work
    folder: markdown-paintings
    create: true
    slug: "{{slug}}"
    fields:
      - name: Image
        label: Image
        widget: image
        default: null
        allow_multiple: true
        media_library:
          config:
            multiple: true
      - { name: title, label: Title }
      - {
          name: height,
          label: Height (inches),
          widget: number,
          valueType: float,
        }
      - { name: width, label: Width (inches), widget: number, valueType: float }
      - { name: depth, label: Depth (inches), widget: number, valueType: float }
      - {
          name: price,
          label: Price ($),
          required: false,
          widget: number,
          valueType: int,
        }
      - {
          name: saatchiLink,
          label: Link to Saatchi Art,
          required: false,
          widget: string,
        }
      - {
          name: moreInfo,
          label: More information,
          required: false,
          widget: markdown,
        }
      - { name: date, label: Date, required: false, widget: date }
  - name: collection
    label: Collection of Works
    folder: markdown-collections
    create: true
    slug: "collection_{{slug}}"
    fields:
      - { name: title, label: Title }
      - label: Images
        name: images
        widget: list
        fields:
          - {
              label: Image,
              name: Image,
              widget: relation,
              collection: painting,
              searchFields: [title],
              valueField: title,
              default: null,
            }
      - { name: date, label: Date, required: false, widget: date }
      - {
          name: saatchiLink,
          label: Link to Saatchi Art,
          required: false,
          widget: string,
        }
      - {
          name: moreInfo,
          label: More information,
          required: false,
          widget: markdown,
        }
