backend:
  name: github
  repo: dcorn068/hyeranart

# https://www.netlifycms.org/docs/configuration-options/#media-library
media_folder: static/images/uploads
public_folder: images/uploads
media_library:
  name: cloudinary
  config:
    cloud_name: dypooxy9q
    api_key: 857318985278727
site_url: https://hyeranart.netlify.com

collections:
  - name: painting
    label: Single Work
    folder: markdown-paintings
    create: true
    fields:
      - name: Image
        label: Image
        widget: image
        default: null
        media_library:
          config:
            multiple: false
      - { name: title, label: Title }
      - { name: path, label: Path (web address after / e.g. my-work-name) }
      - { name: date, label: Date, required: false, widget: datetime }
      - { name: caption, label: Caption, required: false, widget: markdown }
      - {
          name: moreInfo,
          label: More information,
          required: false,
          widget: markdown,
        }
      - {
          name: price,
          label: Price ($),
          required: false,
          widget: number,
          valueType: int,
        }
  - name: collection
    label: Collection of Works
    folder: markdown-collections
    create: true
    fields:
      - name: Image
        label: Image
        widget: image
        default: null
        media_library:
          config:
            multiple: true
      - { name: title, label: Title }
      - {
          name: path,
          label: Path (web address after / e.g. my-collection-name),
        }
      - { name: date, label: Date, required: false, widget: datetime }
      - { name: caption, label: Caption, required: false, widget: markdown }
      - {
          name: moreInfo,
          label: More information,
          required: false,
          widget: markdown,
        }
      - {
          name: price,
          label: Price ($),
          required: false,
          widget: number,
          valueType: int,
        }
